import car_0 from "../assets/cars/car_0.png";
import car_1 from "../assets/cars/car_1.png";
import car_2 from "../assets/cars/car_2.png";
import car_3 from "../assets/cars/car_3.png";
import car_4 from "../assets/cars/car_4.png";
import car_5 from "../assets/cars/car_5.png";
import car_6 from "../assets/cars/car_6.png";
import car_7 from "../assets/cars/car_7.png";
import car_8 from "../assets/cars/car_8.png";
import car_11 from "../assets/cars/car_11.png";
import car_10 from "../assets/cars/car_10.png";
const cars = [
    {
        name :  "Honda Civic",
        type : "Sport",
        image : car_7,
        isFavorite : true,
        price : 99.00,
        oldPrice : -1,
        seats : 4,
        transition : "Automatic",
        fuel : 90,
      },
      {
        name :  "Toyota Axio",
        type : "Sport",
        image : car_8,
        isFavorite : false,
        price : 80.00,
        oldPrice : 100.00,
        seats : 2,
        transition : "Automatic",
        fuel : 80,
      },
      {
        name :  "Honda CRV",
        type : "Sedan",
        image : car_3,
        isFavorite : true,
        price : 96.00,
        oldPrice : -1.00,
        seats : 4,
        transition : "Manual",
        fuel : 70,
      },
      {
        name :  "KIA Sporatge",
        type : "SUV",
        image : car_10,
        isFavorite : false,
        price : 72.00,
        oldPrice : 80.00,
        seats : 6,
        transition : "Manual",
        fuel : 70,
      },
      {
        name :  "CR - V",
        type : "SUV",
        image : car_5,
        isFavorite : true,
        price : 80.00,
        oldPrice : -1,
        seats : 6,
        transition : "Manual",
        fuel : 80,
      },
      {
        name :  "All New Terios",
        type : "SUV",
        image : car_6,
        isFavorite : false,
        price : 74.00,
        oldPrice : -1,
        seats : 6,
        transition : "Manual",
        fuel : 90,
      },
      //
      {
        name :  "Koenigsegg",
        type : "Sport",
        image : car_0,
        isFavorite : true,
        price : 99.00,
        oldPrice : -1,
        seats : 2,
        transition : "Automatic",
        fuel : 90,
      },
      {
        name :  "Nossan GT-R",
        type : "Sport",
        image : car_1,
        isFavorite : false,
        price : 80.00,
        oldPrice : 100.00,
        seats : 2,
        transition : "Automatic",
        fuel : 80,
      },
      {
        name :  "Rolls-Roys",
        type : "Sedan",
        image : car_3,
        isFavorite : true,
        price : 96.00,
        oldPrice : -1.00,
        seats : 4,
        transition : "Manual",
        fuel : 70,
      },
      {
        name :  "All New Rush",
        type : "SUV",
        image : car_4,
        isFavorite : false,
        price : 72.00,
        oldPrice : 80.00,
        seats : 6,
        transition : "Manual",
        fuel : 70,
      },
      {
        name :  "CR - V",
        type : "SUV",
        image : car_5,
        isFavorite : true,
        price : 80.00,
        oldPrice : -1,
        seats : 6,
        transition : "Manual",
        fuel : 80,
      },
      {
        name :  "All New Terios",
        type : "SUV",
        image : car_6,
        isFavorite : false,
        price : 74.00,
        oldPrice : -1,
        seats : 6,
        transition : "Manual",
        fuel : 90,
      },
      //
      {
        name :  "Koenigsegg",
        type : "Sport",
        image : car_0,
        isFavorite : true,
        price : 99.00,
        oldPrice : -1,
        seats : 2,
        transition : "Automatic",
        fuel : 90,
      },
      {
        name :  "Nossan GT-R",
        type : "Sport",
        image : car_1,
        isFavorite : false,
        price : 80.00,
        oldPrice : 100.00,
        seats : 2,
        transition : "Automatic",
        fuel : 80,
      },
      {
        name :  "Rolls-Roys",
        type : "Sedan",
        image : car_3,
        isFavorite : true,
        price : 96.00,
        oldPrice : -1.00,
        seats : 4,
        transition : "Manual",
        fuel : 70,
      },
      {
        name :  "All New Rush",
        type : "SUV",
        image : car_4,
        isFavorite : false,
        price : 72.00,
        oldPrice : 80.00,
        seats : 6,
        transition : "Manual",
        fuel : 70,
      },
      {
        name :  "CR - V",
        type : "SUV",
        image : car_5,
        isFavorite : true,
        price : 80.00,
        oldPrice : -1,
        seats : 6,
        transition : "Manual",
        fuel : 80,
      },
      {
        name :  "All New Terios",
        type : "SUV",
        image : car_6,
        isFavorite : false,
        price : 74.00,
        oldPrice : -1,
        seats : 6,
        transition : "Manual",
        fuel : 90,
      },
      {
        name :  "Koenigsegg",
        type : "Sport",
        image : car_0,
        isFavorite : true,
        price : 99.00,
        oldPrice : -1,
        seats : 2,
        transition : "Automatic",
        fuel : 90,
      },
      {
        name :  "Nossan GT-R",
        type : "Sport",
        image : car_1,
        isFavorite : false,
        price : 80.00,
        oldPrice : 100.00,
        seats : 2,
        transition : "Automatic",
        fuel : 80,
      },
      {
        name :  "Rolls-Roys",
        type : "Sedan",
        image : car_3,
        isFavorite : true,
        price : 96.00,
        oldPrice : -1.00,
        seats : 4,
        transition : "Manual",
        fuel : 70,
      },
      {
        name :  "All New Rush",
        type : "SUV",
        image : car_4,
        isFavorite : false,
        price : 72.00,
        oldPrice : 80.00,
        seats : 6,
        transition : "Manual",
        fuel : 70,
      },
      {
        name :  "CR - V",
        type : "SUV",
        image : car_5,
        isFavorite : true,
        price : 80.00,
        oldPrice : -1,
        seats : 6,
        transition : "Manual",
        fuel : 80,
      },
      {
        name :  "All New Terios",
        type : "SUV",
        image : car_6,
        isFavorite : false,
        price : 74.00,
        oldPrice : -1,
        seats : 6,
        transition : "Manual",
        fuel : 90,
      },
]

export function getCarArray(limit){
    if(limit){
        return cars.slice(0,limit);
    }
    return cars;
}

export function getCar(index){
    return cars[index];
}